# Generated by Django 5.2.1 on 2025-05-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(default='aucun', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default='Aucun'),
            preserve_default=False,
        ),
    ]
